name: CI - Streamlit App

on:  
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential  

      - name: Install numpy and cython first
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install cython

      - name: Install scikit-surprise from source
        run: |
          pip install scikit-surprise --no-binary :all:

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest tests/